name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-analyze-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up CMake environment
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.22.1'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential lcov

    # Step 4: Configure the build directory with Debug mode
    - name: Configure CMake with Coverage
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    # Step 5: Build the project
    - name: Build with CMake
      run: cmake --build build --config Debug
      
    # Step 6: Run tests
    - name: Run tests
      run: ctest --test-dir build/tests/

    # Step 7: Generate coverage
    - name: Generate coverage
      run: |
        lcov --ignore-errors source --capture --directory build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info

    # Step 8: Run SonarQube analysis
    - uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
